### ISSUE TITLE
Stream-M and Wirecast 6.0.4

### ISSUE THREAD

**Issue by JimPear** [vbence/stream-m#10]
Hello,

I'd like to use Stream-M with Wirecast v6.0.4 (http://www.telestream.net/wirecast/overview.htm) but i have some issues. 

I'm trying to deploy a Stream-M server on a first machine locally (with the IP : 10.0.0.1 and using "java -jar stream-m.jar server.properties" command) then i use Wirecast on another PC (ex : 10.0.0.2) and configure the connexion RTMP to broadcast the video stream with the following URI : 
rtmp://10.0.0.1:8081/publish/<streamname>?<streampass>

But the broadcast doesn't work (the stream button blinked and displayed a connexion error) but i don't understand why because i can ping and i can reach my server from my browser with my 10.0.0.2 machine. I tried to telnet and it worked too. 

When i try to broadcast the stream, the following error appears on my server console : 
Exception in thread "Thread-10" java.lang.RuntimeException: java.net.SocketException: Connection reset
	at org.czentral.util.stream.Feeder.feedTo(Feeder.java:78)
	at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.czentral.util.stream.Feeder.feedTo(Feeder.java:70)
	... 1 more

I don't know what can i do to solve this problem :(
Do you guys have any problems like this using RTMP with Wirecast or another similar software ? Any ideas to help me ? 

PS : Sorry for my bad english i'm french ^^

**Comment by vbence** [comment]
Thanks for the report. I will track Wirecast compatibility in issue #9 - please follow that one for updates.

**Comment by vbence** [comment]
Hi Jim, can you please test v0.2.2?
