### ISSUE TITLE
Streaming RTMP from vlc

### ISSUE THREAD

**Issue by zoltan-fedor** [vbence/stream-m#12]
Hi,
I'm trying to use vlc to stream rtmp to stream-m. Unfortunately can't use ffmpeg due to a bug related to Logitech C920 (see http://stackoverflow.com/questions/30765700/ffserver-streaming-h-264-from-logitech-c920-without-re-encoding/30779835#30779835 )

When I try the below vlc streams to stream to stream-m running on a different server, stream-m shows:
`Processor finished.`
`metadata: [@setDataFrame, onMetaData, {duration=0.0, videocodecid=7.0, framerate=30.0, width=1920.0, videodatarate=0.0, filesize=0.0, encoder=Lavf54.20.4, height=1088.0}]`
`Exception in thread "Thread-34" java.lang.ArrayIndexOutOfBoundsException: 1`
`at  org.czentral.incubator.streamm.PublisherAppInstance.mediaChunk(PublisherAppInstance.java:295)`
`at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:179)`
`at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:129)`
`at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)`
`at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)`
`at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)`
`at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)`

VLC is called with:
`cvlc v4l2:///dev/video0:chroma=h264:width=1920:height=1080 --sout '#standard{access=rtmp,mux=ffmpeg{mux=flv},dst=rtmp://10.65.xx.xx:8081/publish/first?secret}' -vvv`

While vlc shows:
`[0xb0300560] main input debug: 'v4l2:///dev/video0:chroma=h264:width=1920:height=1080' successfully opened`
`[0xb0300560] main input debug: Buffering 0%`
`[0xb0300560] main input debug: switching to sync mode`
`[0xb014c3b0] packetizer_h264 decoder debug: found NAL_SPS (sps_id=0)`
`[0xb014c3b0] packetizer_h264 decoder debug: found NAL_PPS (pps_id=0 sps_id=0)`
`[0xb0300560] main input debug: Buffering 10%`
`[0xb0100760] main stream output debug: adding a new sout input (sout_input:0xadc00538)`
`[0xb013cb28] main mux debug: adding a new input`
`[0xb013cb28] avformat mux debug: adding inputo`  
`[0xb0300560] main input debug: Buffering 21%`
`[0xb0300560] main input debug: Buffering 33%`
`[0xb0300560] main input debug: Buffering 43%`
`[0xb0300560] main input debug: Buffering 54%`
`[0xb0300560] main input debug: Buffering 66%`
`[0xb0300560] main input debug: Buffering 77%`
`[0xb0300560] main input debug: Buffering 87%`
`[0xb0300560] main input debug: Buffering 99%`
`[0xb0300560] main input debug: Stream buffering done (331 ms in 331 ms)`
`[0xb0300560] main input debug: Decoder buffering done in 0 ms`
`[0xb013cb28] avformat mux debug: writing header`
`[flv @ 0xb013d180] Codec for stream 0 does not use global headers but container format requires global headers`

And when loading http://xxxx.com:8080/consume/first it shows `Stream Not Running`

Any idea?

**Comment by vbence** [comment]
Hi Zoltan, thanks for your feedback. Unfortunately I can not get v4l2 fetch h264 frames from my C920-C (only `yuyv422` and `mjpeg` shows up). Which distribution are you using?

Alternatively it would also help if you could save a few seconds from your raw h264 input in TS format and upload somewhere for me.

**Comment by vbence** [comment]
Also.. I'm a bit concerned about C920's keyframe interval. I do not think it is using something that is ideal for live streaming. - A 2 second (60 frames or so) interval would be best or else there is too much data as a single GOP is always buffered by the server (only way a fragmented MP4 can be muxed).

**Comment by zoltan-fedor** [comment]
Hi Bence,
Thanks for the reply. Yes, the C920-C cannot do .H264 on the hardware, but the C920 can.
This is what I have: http://www.amazon.com/Logitech-Webcam-Widescreen-Calling-Recording/dp/B006JH8T3S/ref=sr_1_1?ie=UTF8&qid=1435072123&sr=8-1&keywords=c920

Regarding the keyframes. I have never realized, but it sounds like the C920 might be sending keyframes only once in 10 seconds (once in 300 frames) by default (see https://www.raspberrypi.org/forums/viewtopic.php?t=60136&p=463607), but this might be something what could be changed, I will have to look into that.

I took a quick 6 second stream in the raw h264 as it comes out of the C920 and uploaded it to http://broadcast-this.com/c920/

**Comment by vbence** [comment]
Ok. I managed to reproduce the problem. Stay tuned.

**Comment by vbence** [comment]
I relaxed some checks and limits. There is still a weird error, but I suspect it is only at the end of the stream. You should be fine as long as the stream is running.

The latest master should contain these changes. Let me know if you have problems compiling it.

**Comment by zoltan-fedor** [comment]
Thanks for the fix. Unfortunately I didn't compile it before, so I don't have it setup, so that might take a while.
If it is easy for your to compile the new master, then I would appreciate that.

**Comment by vbence** [comment]
Here you go.
http://www.czentral.org/stream-m/stream-m-20150630-0925.zip

**Comment by zoltan-fedor** [comment]
Thanks.

I have tested with this new version, but unfortunately still no good, this time the error from stream-m is

> $ java -jar stream-m.jar server.properties 
metadata: [@setDataFrame, onMetaData, {duration=0.0, videocodecid=7.0, framerate=30.0, width=1920.0, videodatarate=0.0, filesize=0.0, encoder=Lavf54.20.4, height=1088.0}]
Exception in thread "Thread-2" java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.MovieBox#content].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:59)
	at org.czentral.incubator.streamm.PublisherAppInstance.startStream(PublisherAppInstance.java:432)
	at org.czentral.incubator.streamm.PublisherAppInstance.mediaChunk(PublisherAppInstance.java:362)
	at org.czentral.minirtmp.ApplicationContext.processMessage(ApplicationContext.java:179)
	at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:122)
	at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:207)
	at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
	at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
	at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.TrackBox#content].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:54)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 12 more
Caused by: java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.MediaBox#content].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:54)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 17 more
Caused by: java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.MediaInformationBox#content].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:54)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 22 more
Caused by: java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.SampleTableBox#content].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:54)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 27 more
Caused by: java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.SampleDescriptionBox#content].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:54)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 32 more
Caused by: java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.VisualSampleEntry#content].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:54)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 37 more
Caused by: java.lang.RuntimeException: Unable to serialize filed [org.czentral.format.mp4.GeneralBoxImpl#bytes].
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:116)
	at org.czentral.data.binary.serializer.AnnotatedClass.serialize(AnnotatedClass.java:66)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:54)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 42 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32768
	at org.czentral.data.binary.serializer.FixedInteger.serialize(FixedInteger.java:71)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:93)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeWithType(GeneralSerializer.java:101)
	at org.czentral.data.binary.serializer.GeneralSerializer.serializeSingle(GeneralSerializer.java:70)
	at org.czentral.data.binary.serializer.GeneralSerializer.serialize(GeneralSerializer.java:49)
	at org.czentral.data.binary.serializer.AnnotatedClass.serializeWithType(AnnotatedClass.java:114)
	... 47 more
Exception in thread "Thread-13" java.lang.NullPointerException
	at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)

**Comment by vbence** [comment]
This is s step forward (we are already on the output/muxing side). I have a suspicion what might happen, but I will need a little longer sample to test it (if you suspect keyframe interval of 10 secons, a 22 seconds long video should do it).

**Comment by zoltan-fedor** [comment]
Thanks!
I have added two more longer examples to http://broadcast-this.com/c920/
I still couldn't figure out how to make this C920 to add keyframes more frequently.

**Comment by zoltan-fedor** [comment]
Did the additional examples help? Do you need some more?

**Comment by vbence** [comment]
Yes, sorry for the slow progress. Here is what I could collect this far:

It seems like frame data is damages/lost somewhere in the pipeline. The samples, if you watch them with ffplay or vlc, stutter a low, the image breaks up etc.

VLC is not very good at handling this stream and produces errorneous RTMP output, where frame data "bleeds out" from the frames into protocol space and essentially gets the RTMP parser off the rails. With some tolerance it can find its way back to the correct offset and continue parsing the stream, but the frames are too damaged to be reconstructed.

I managed to get my hands on a C930e. While `v4l2-ctl --list-formats` still does not list the H264 pixel format, I managed to get a stream off the camera with `guvcview`. This might be a Linux thing, but I also got broken frames all the time (no such problems when using MJPEG; only with H.264).

I will play around a little bit more with it, but from what I got this far I would recommend you look after alternative hardware encoding solutions. You can use the *QuickSync* abilities of a chep Intel Celeron through VA/API dirver, or the circuit inside a Raspbery PI through OpenMAX API. - Both are supported through GStreamer filters.

Just to close out all other possibilities (like this being some TS-specific artifact)... can you please upload an other sample using MP4 container?

Thanks for your help!
