### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by czerep1991** [vbence/stream-m#9]
Connect RTMP from Wirecast
Exception in thread "Thread-2" java.lang.RuntimeException: java.net.SocketException: Connection reset
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:78)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:70)
        ... 1 more

**Comment by vbence** [comment]
The RTMP implementation in Stream-m is by far not complete. Wirecast must be more squeamish with the protocol. I will do some wiresharking and get back to you on the weekend.

**Comment by vbence** [comment]
Can you please check if the issue is still present in the latest version?

**Comment by czerep1991** [comment]
Issuse don't solved problem:
Exception in thread "Thread-19" java.lang.RuntimeException: java.net.SocketException: Connection reset
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:78)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:70)
        ... 1 more

**Comment by vbence** [comment]
Confirmed. It seems like I uploaded the wrong version. Please stand by for a re-uploaded version.

**Comment by czerep1991** [comment]
Good now wirecast can connect but i have another problem, if i start watching then server is crash.

metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=240.0, audiodatarate=192.0, height=720.0, audiosamplerate=44100.0, audiochannels=2.0, width=1280.0, videodatarate=2025.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-6" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
Exception in thread "Thread-8" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=240.0, audiodatarate=192.0, height=720.0, audiosamplerate=44100.0, audiochannels=2.0, width=1280.0, videodatarate=2025.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-11" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
Exception in thread "Thread-9" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:118)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Exception in thread "Thread-13" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=240.0, audiodatarate=128.0, height=576.0, audiosamplerate=44100.0, audiochannels=2.0, width=1024.0, videodatarate=1500.0, videocodecid=avc1, framerate=25.0}]
Exception in thread "Thread-16" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)

**Comment by vbence** [comment]
The error message is quite cryptic - sorry for that. You have to use a smaller keyframe interval, please try 60 (instead of the current 240).

**Comment by czerep1991** [comment]
I'm testing on different options, but it does not work when I start to play. I run stream-m on linux debian if you want i can send you a pass to testing account.

Exception in thread "Thread-2" java.lang.RuntimeException: java.net.SocketException: Connection reset
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:78)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:70)
        ... 1 more
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=240.0, audiodatarate=192.0, height=720.0, audiosamplerate=44100.0, audiochannels=2.0, width=1280.0, videodatarate=2025.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:118)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=60.0, audiodatarate=96.0, height=600.0, audiosamplerate=44100.0, audiochannels=2.0, width=800.0, videodatarate=1024.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-7" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
Exception in thread "Thread-5" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:118)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=50.0, audiodatarate=96.0, height=600.0, audiosamplerate=44100.0, audiochannels=2.0, width=800.0, videodatarate=640.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-14" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
Exception in thread "Thread-12" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:118)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Exception in thread "Thread-2" java.lang.RuntimeException: java.net.SocketException: Connection reset
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:78)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:70)
        ... 1 more
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=240.0, audiodatarate=192.0, height=720.0, audiosamplerate=44100.0, audiochannels=2.0, width=1280.0, videodatarate=2025.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:118)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=60.0, audiodatarate=96.0, height=600.0, audiosamplerate=44100.0, audiochannels=2.0, width=800.0, videodatarate=1024.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-7" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
Exception in thread "Thread-5" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:118)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)
metadata: [@setDataFrame, onMetaData, {audiocodecid=mp4a, videokeyframe_frequency=50.0, audiodatarate=96.0, height=600.0, audiosamplerate=44100.0, audiochannels=2.0, width=800.0, videodatarate=640.0, videocodecid=avc1, framerate=30.0}]
Exception in thread "Thread-14" java.lang.NullPointerException
        at org.czentral.minihttp.MiniHTTP$Worker.run(MiniHTTP.java:108)
Exception in thread "Thread-12" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.czentral.minirtmp.ApplicationContext.processChunk(ApplicationContext.java:118)
        at org.czentral.minirtmp.RTMPStreamProcessor.processPacket(RTMPStreamProcessor.java:206)
        at org.czentral.minirtmp.RTMPStreamProcessor.process(RTMPStreamProcessor.java:75)
        at org.czentral.util.stream.Feeder.feedTo(Feeder.java:56)
        at org.czentral.minirtmp.MiniRTMP$Worker.run(MiniRTMP.java:95)

**Comment by vbence** [comment]
Your snippet shows the keyframe interval is still too high. Please see Step 4 in this article:
http://support.metacdn.com/hc/en-us/articles/204513925-How-To-Broadcast-A-Live-Stream-Using-Telestream-Wirecast

Setting it to 60 should solve the issue.
